# Listener para conexões MQTT padrão (porta 1883)
listener 1883 0.0.0.0
allow_anonymous true
persistence true

# Listener para WebSockets (porta 9001 - usada pelo navegador)
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true